call plug#begin('~/.vim/plugged')
Plug 'https://github.com/universal-ctags/ctags.git'
call plug#end()

"# tabs shows as > for the start position and - through the rest of the tab
set list
set listchars=tab:>-

set tags=./.tags;,.tags
set number
set tabstop=4
set shiftwidth=4
set expandtab
"set autoindent
